tinymce.PluginManager.add('addquicktags', function(editor) {

	var csMenuItems = [
		{ text: 'ヘッド(白字・画像背景)', data: '<table class="head-w" style="background-image: url(\'http://lptemp.com/dx/wp-content/uploads/2013/11/headback_moutain.jpg\'); height: 400px;" border="0">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: 60px;">ヘッドの文字を入力</span></p>\n<p>補足説明</p>\n<p>補足説明</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'ヘッド(黒字・画像背景)', data: '<table class="head-b" style="background-image: url(\'http://lptemp.com/dx/wp-content/uploads/2013/11/headback_letter1.jpg\'); height: 400px;" border="0">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: 60px;">ヘッドの文字を入力</span></p>\n<p>補足説明</p>\n<p>補足説明</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'サブヘッド(白字)', data: '<table class="obi" style="background-color: #ce1219;" border="0">\n<tbody>\n<tr>\n<td>\n<p>文字</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'サブヘッド(黒字)', data: '<table class="obi-b" style="background-color: #ffff33;" border="0">\n<tbody>\n<tr>\n<td>\n<p>文字</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '小見出し', data: '<table style="background-color: #f0f0f0;  height: 70px;">\n<tbody>\n<tr>\n<td style="padding: 0 10px;">ここに文字を入力</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'フォーム大', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" alt="torokuword1" src="http://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" width="800" height="104" /></p>\n<form action="http://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /> <input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[1]" value="名前を入力" /></dd><dt>メールアドレス</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[0]" value="メールアドレスを入力" /></dd></dl>\n<div class="btn"><input class="btn-blue" type="submit" name="submit" value="　登録　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'フォーム小', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px; width: 420px;" border="2" frame="border" rules="all" align="right">\n<tbody>\n<tr>\n<td style="width: 380px;"><form action="http://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /><input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd></dd><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[1]" value="名前を入力" /></dd><dt>メールアドレス</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[0]" value="メールアドレスを入力" /></dd></dl>\n<div class="btn"><input class="btn-blue-sma" type="submit" name="submit" value="　登録　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p><img class="alignnone size-full wp-image-75" alt="torokuword-sma1" src="http://lptemp.com/dx/wp-content/uploads/2013/11/torokuword-sma1.png" width="370" height="400" /></p>\n<p>&nbsp;</p>'},
		{ text: 'フォーム大(ボタン画像ver)', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" alt="torokuword1" src="http://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" width="800" height="104" /></p>\n<form action="http://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /> <input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[1]" value="名前を入力" /></dd><dt>メールアドレス</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[0]" value="メールアドレスを入力" /></dd></dl>\n<div class="btn"><input type="image" name="submit" src="http://lptemp.com/dx/wp-content/uploads/2013/11/button1_blue_big.jpg" value="　今すぐ無料で登録する　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'フォーム小(ボタン画像ver)', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px; width: 420px;" border="2" frame="border" rules="all" align="right">\n<tbody>\n<tr>\n<td style="width: 380px;"><form action="http://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /><input type="hidden" name="fid" value="example" /><input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd></dd><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[1]" value="名前を入力" /></dd><dt>メールアドレス</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[0]" value="メールアドレスを入力" /></dd></dl>\n<div class="btn"><input type="image" name="submit" src="http://lptemp.com/dx/wp-content/uploads/2013/11/button1_blue_sma.jpg" value="　今すぐ無料で登録する　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p><img class="alignnone size-full wp-image-75" alt="torokuword-sma1" src="http://lptemp.com/dx/wp-content/uploads/2013/11/torokuword-sma1.png" width="370" height="400" /></p>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(四角)', data: '<table class="shikaku" style="border: 1px solid #000000;" border="1">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span><span><span style="color: #ff0000; font-size: large;"><b><br /></b></span></span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span><span style="font-size: large;">ここに文字を入力</span></p>\n<p><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　<span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span></p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(角丸)', data: '<table class="marukaku" style="border: 1px solid #000000;" border="1">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span><span><span style="color: #ff0000; font-size: large;"><b><br /></b></span></span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span><span style="font-size: large;">ここに文字を入力</span></p>\n<p><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　<span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span></p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(へこみ)', data: '<table class="pressed">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span><span><span style="color: #ff0000; font-size: large;"><b><br /></b></span></span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span><span style="font-size: large;">ここに文字を入力</span></p>\n<p><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　<span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span></p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(浮出)', data: '<table class="tableshadow">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span><span><span style="color: #ff0000; font-size: large;"><b><br /></b></span></span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><strong><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span></strong><span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span><span style="font-size: large;">ここに文字を入力</span></p>\n<p><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　<span style="font-size: large;">ここに文字を入力</span></p>\n<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</span></p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'ブレッド追加', data: '<p><span style="font-size: large;"><img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　</span><span style="font-size: large;">ここに文字を入力</span></p>'},
		{ text: 'ボタン(青大)', data: '<p class="btn-blue"><a href="http://yahoo.jp" target="blank">ここに好きな文字を入力</a></p>\n<p>&nbsp;</p>'},
		{ text: 'ボタン(青小)', data: '<p class="btn-blue-sma"><a href="http://yahoo.jp"target="blank">ここに好きな文字を入力</a></p>\n<p>&nbsp;</p>'},
		{ text: 'チェックマーク(緑)', data: '<img alt="1540_32" src="http://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />'},
		{ text: '下矢印(青)', data: '<img  src="http://lptemp.com/dx/wp-content/uploads/2013/11/allow.jpg" />'},
		{ text: '特商法等の記載', data: '<p style="text-align: center;"><span style="font-size: x-small;"><a href="http://yahoo.co.jp" target="_blank">特定商取引法の表記</a>　｜　<a href="http://yahoo.co.jp" target="_blank">プライバシーポリシー</a>　｜　<a href="http://yahoo.co.jp" target="_blank">利用規約</a></span></p>'},
		{ text: 'コピーライト', data: '<p style="text-align: center;"><span style="font-size: small;">Copyright (C) 20○○ あなたの社名など All Rights Reserved.</span></p>'},
		{ text: '大きいサイズの文字', data: '<p style="font-size: 80px;">大きいサイズ</p>'},
		{ text: 'ホバーサンプル1', data: '<p style="text-align: center;"><strong style="font-size: 40px;">ちょっと待ってください</strong></p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>&nbsp;</p>\n<table class="formsubmit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 250px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" alt="torokuword1" src="http://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" width="500" /></p>\n<form action="http://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /> <input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[1]" value="名前を入力" /></dd><dt>メールアドレス</dt><dd><input class="focus" style="color: #969696; font-size: 100%;" type="text" name="d[0]" value="メールアドレスを入力" /></dd></dl>\n<div class="btn"><input type="submit" name="submit" value="　　無料で登録する　　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>'},
		{ text: '表(ラインあり)', data: '<table class="line" border="0">\n<tbody>\n<tr>\n<td> </td>\n<td> </td>\n</tr>\n<tr>\n<td> </td>\n<td> </td>\n</tr>\n<tr>\n<td> </td>\n<td> </td>\n</tr>\n<tr>\n<td> </td>\n<td> </td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠(幅いっぱい)', data: '<table class="wide" style="background-image: url(\'http://lptemp.com/dx/wp-content/uploads/2013/12/rockywall.png\'); ">\n<tbody>\n<tr>\n<td>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '(高度)全幅ヘッド', data: '<div class="full-width">\n<table class="head-w" style="border-width: 0px; border-style: solid; background-image: url(\'http://lptemp.com/dx/wp-content/uploads/2014/10/blur-background13.jpg\');  background-position: 50% 0; height: 400px;" border="0">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: 60px;">ヘッドの文字を入力</span></p>\n<p>補足説明</p>\n<p>補足説明</p>\n</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>&nbsp;</p>'},
		{ text: '(高度)全幅枠', data: '<div class="full-width">\n<table style="background-color: #ffd464;   background-position: 50% 0; border-width: 0px; border-style: solid;" border="0">\n<tbody>\n<tr>\n<td>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>&nbsp;</p>'},
		{ text: 'ページ内カウントダウン', data: '<p>[innerCountdown]</p>\n<p>&nbsp;</p>'},
		
	];

	function insertTag(data) {
		editor.insertContent(data);
	}

	editor.addButton('taglist', {
		type: 'menubutton',
		text: 'カスタムボタン',
		icon: false,
		menu: csMenuItems,
		onselect: function(e) {
			insertTag(e.control.settings.data);
		},
	});

});
